### ISSUE TITLE
Add disambiguation to the Institution selector where multiple organisations of the same name exist

### ISSUE THREAD

**Issue by spaetow** [geteduroam/ionic-app#109]
The CAT website selector provides a basic filtering mechanism through Discojuice by defaulting to the UK (for me). However, geteduroam does not have that functionality. 

I am looking at two Boston Colleges, one in the UK and one in the US. On the website, because of the above filtering, it only shows me the UK (which is what is expected), and only when I choose 'all countries' that it shows me the second one. 

<img width="519" alt="Screenshot 2021-11-30 at 18 28 18" src="https://user-images.githubusercontent.com/4982349/144106845-60373dde-b797-4d8a-bc13-eb939a157ac5.png">

geteduroam shows me this:
<img width="519" alt="Screenshot_20211130-182933" src="https://user-images.githubusercontent.com/4982349/144106876-36e6e4e3-6aea-42d9-8c02-453e29d05a60.png">

As you can see, there is no disambiguation (possibly with a "(Country Name)" after the name). So users will be... playing roulette. This needs improving.

**Comment by jornane** [comment]
I think we could add the country to names that aren't unique, so you'd get something like Boston College [UK] and Boston College [US]. We can change this in the importer from CAT so it would not require an update to the app.

For a newer version of the discovery, we should consider this case better.

**Comment by jornane** [comment]
We fixed it :)

**Comment by spaetow** [comment]
Fantastic. That works for me. :-)
