### ISSUE TITLE
GNU/Linux support

### ISSUE THREAD

**Issue by hex-m** [geteduroam/ionic-app#114]
The [website](https://www.geteduroam.app/download/) says:

> Solutions for macOS and the *NIXes are still being developed, please stay tuned

While there is a [dedicated repository](https://github.com/geteduroam/macos-app) for macOS, I can't find anything related to GNU/Linux. Are there plans to build this Iconic-App for GNU/Linux desktop users?

**Comment by agomezmoron** [comment]
Hi @hex-m if you are interested on building something similar, I have a WIP node library that could be use for a Desktop app by using electron for example: https://github.com/agomezmoron/node-wifi-handler

**Comment by jornane** [comment]
We have a [Linux app](/geteduroam/linux-app) now.
