### ISSUE TITLE
Handle redirect in discovery

### ISSUE THREAD

**Issue by jornane** [geteduroam/ionic-app#19]
In the latest version of Cattenbak, we've added support for redirect profiles from CAT. This means that the discovery may contain a simple `redirect` field for a profile, which means that the app should offer the user the provided link and open a browser when pressed. The flow ends there.

After adding these to the discovery, I noticed that the app hangs on these profiles (busy animation never terminates). Of course it makes sense that the app doesn't support this feature that did not exist when it was made, but it should crash more explicitly when anything is wrong.

**Comment by jornane** [comment]
Completion criteria:

1) App must NEVER crash or hang due to unexpected or missing values in discovery, but should show an error message that the institution is not supported
2) Redirect fields in the discovery lead to a page stating that the app cannot be used for this institution, but instructions on how to configure eduroam are available on the link.

**Comment by CarlosFJ** [comment]
#53

**Comment by CarlosFJ** [comment]
Fixed in commit #53

**Comment by CarlosFJ** [comment]
Handled in commit c5fefc303e5bf2fab7ef9c750d57576e0551aeee

**Comment by CarlosFJ** [comment]
I updated branch to open url outside the app.
