### ISSUE TITLE
Support multiple SSIDs

### ISSUE THREAD

**Issue by jornane** [geteduroam/ionic-app#24]
An eap-config can contain more than one `<IEEE80211>`, and each of these can contain an `<SSID>` block ([specification](https://github.com/GEANT/CAT/blob/v2.0.3/devices/xml/eap-metadata.xsd#L172-L187)). The app must configure every SSID with the configuration from the configuration file.

Also, if no `<SSID>` is set, the app must NOT assume an SSID such as `eduroam`. A profile can be HS20-only and not have any SSID.

If the profile contains no `<SSID>` and no `<ConsortiumOID>`, the profile is invalid and the app should emit an error.

**Comment by jornane** [comment]
The app [currently has a default SSID](https://github.com/geteduroam/ionic-app/blob/develop/src/src/providers/global/global.ts#L36-L41), this must be removed.

**Comment by agomezmoron** [comment]
This was merged into develop by Paul

**Comment by pauldekkers** [comment]
Because it works! ;-)
