### ISSUE TITLE
HS20 using API 28

### ISSUE THREAD

**Issue by jornane** [geteduroam/ionic-app#43]
Android supports HS20 in API 28, we need a version of the app with HS20 and API 28

**Comment by agomezmoron** [comment]
We all agreed to:

1. Try to configure HS20 with addOrUpdate method.
2. If that fails:
    2.1. If we have a SSID, configure as part of the Network configuration.
    2.2. If we don't have a SSID, we will configure as #Passpoint

**Comment by amachadogarcia** [comment]
Fixed in commit 7bdec46980d3c91b5f2032f349a171759155af0f
