### ISSUE TITLE
REGRESSION: App attempts to configure SSID #Passpoint

### ISSUE THREAD

**Issue by jornane** [geteduroam/ionic-app#46]
![IMG_37D7AABD1E31-1](https://user-images.githubusercontent.com/767872/94050393-7c645400-fdd6-11ea-80c9-e79675620077.jpeg)

The app attempts to configure the SSID #Passpoint

1. This is **NEVER** needed on iOS
2. The profile also contains an eduroam SSID, so this is **NOT** needed, even on Android

**Comment by agomezmoron** [comment]
It's related to #43. As soon as #43 is accepted, this will be done too.

**Comment by jornane** [comment]
Fixed in another PR
