### ISSUE TITLE
iOS app with geteduroam profile only works for initial connection

### ISSUE THREAD

**Issue by tomyren** [geteduroam/ionic-app#58]
This issue is seen on both geteduroam v 1.0.2 and 1.0.1: 
On initial config the setup works and iPhone connects correctly to eduroam SSID (except during installation user is asked to also configure HS20 - this should be done silently?) 
The problem occurs after switching to a different SSID and then back to eduroam:

1. The App then askes for Username and password (it should not, since using client cert)(So Cancel) 
2. The iPhone then is associated to eduroam, but has no IP address as authentication is not done (can see in AAA server that no auth is sent) 

The result is that App only works the very first time, if the App is used again user can connect once! 
See a few screenshots attached. 
![IMG_3942](https://user-images.githubusercontent.com/26898476/94795879-462e6200-03de-11eb-8956-bc286fb0e73e.png)

First time - all OK. Then connected to a different SSID and back to eduroam: 

![IMG_3943](https://user-images.githubusercontent.com/26898476/94795891-49c1e900-03de-11eb-9fea-ad836d0969f0.png)

Asking for username / password  - should not happen!

![IMG_3944](https://user-images.githubusercontent.com/26898476/94795893-4a5a7f80-03de-11eb-8dcd-886f6fd51e04.png)

Associated - but no connection

![IMG_3945](https://user-images.githubusercontent.com/26898476/94795896-4b8bac80-03de-11eb-9aaa-df531d213552.png)

Received no address - as authentication is not done on second or later connections to eduroam.

**Comment by CarlosFJ** [comment]
About this, the connection is stable ?

**Comment by agomezmoron** [comment]
Covered in #70
