### ISSUE TITLE
either SSID or OIDs are configured on iOS, depending on amount of ConsortiumOIDs in the eap-config

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/ionic-app#64]
With multiple ConsortiumOIDs in the eap-config, roaming networks are configured, NOT SSIDs:
```
⚡️  [log] - {"IEEE80211":[{"SSID":["eduroam"],"MinRSNProto":["CCMP"]},{"ConsortiumOID":["001bc50460"]},{"ConsortiumOID":["004096"]},{"ConsortiumOID":["5A03BA0000"]}]}
```
With one ConsortiumOID in the eap-config, the SSID is configured, and no roaming networks:
```
⚡️  [log] - {"IEEE80211":[{"SSID":["eduroam"],"MinRSNProto":["CCMP"]},{"ConsortiumOID":["001bc50460"]}]}
```
... Did not test multiple SSIDs yet. I assume this only happens on iOS because Passpoint is disabled for Android in this build.

I can use the exact same IdP (like eVA) and change only the ConsortiumOID list and see the effect.

This is with develop as of 76c713e93d0f7b54c7a6e7166e27253b201620d1

**Comment by jornane** [comment]
Might very well be related to #51, possibly the same bug?

**Comment by jornane** [comment]
I tried two quick fixes in `src/src/providers/geteduroam-services/geteduroam-services.ts`

```
# With this change (2x!), the SSID is still NOT configured
-          config['oid'] = resultantProfiles['oidConcat'];
+          config['oid'] = '001bc50460'; // monkey patch, GH#64
```

```
# Just removing the oid alltogether (2x!),
# hereby disabling Hotspot 2.0 entirely
# does fix the SSID issue
-          config['oid'] = resultantProfiles['oidConcat'];
```

**Comment by jornane** [comment]
For eVA, Passpoint works, for Munk, it doesn’t work, and for Uninett Employee network it doesn’t work

SSID works every time
